### ISSUE TITLE
Australia not available in the list of countries

### ISSUE THREAD

**Issue by crohit92** [kondi0/ng4-intl-phone#28] opened 2018-05-10 11:47 UTC
https://github.com/kondi0/ng4-intl-phone/blob/master/src/lib/src/service/country.service.ts
Please add it since it is required

**Comment by cburger** [comment] 2018-07-20 10:08
Duplicate of #21

**Comment by kondi0** [comment] 2022-10-04 16:08
Sorry guys, I was away for a while. Fixed with angular 14 version

**Closed by kondi0** 2022-10-04 16:08 UTC
